export const QUERY = 'QUERY';
export const ADD_CATEGORY = 'ADD_CATEGORY';
export const DELETE_CATEGORY = 'DELETE_CATEGORY';
export const EDIT_CATEGORY = 'EDIT_CATEGORY';
export const REQUEST_CATEGORY = 'REQUEST_CATEGORY';
export const RECEIVE_CATEGORY = 'RECEIVE_CATEGORY';


export const GET_KEYWORD = "GET_KEYWORD";
export const DELETE_KEYWORD = "DELETE_KEYWORD";
export const REQUEST_KEYWORD = "REQUEST_KEYWORD";
export const RECEIVE_KEYWORD = "RECEIVE_KEYWORD";


export const GET_REPORT = "GET_REPORT";
export const DELETE_REPORT= "DELETE_REPORT";
export const REQUEST_REPORT = "REQUEST_REPORT";
export const RECEIVE_REPORT = "RECEIVE_REPORT";